version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      #      - ./test/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  backend:
    image: node:current-alpine3.16
    container_name: backend
    command: npm run start:dev
    working_dir: /var/app/backend
    volumes:
      - ./packages/backend:/var/app/backend
    ports:
      - 3000:3000
    environment:
      EXPOSE_PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: kanban
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: kanban

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
