version: '3.7'
services:
  backend:
    image: node:current-alpine3.16
    container_name: backend
    command: npm run start:dev
    working_dir: /var/app/backend
    volumes:
      - ./packages/backend:/var/app/backend
    ports:
      - 8080:8080
    environment:
      - EXPOSE_PORT=8080